name: Run Gradle Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        run: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --info

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test